### ISSUE TITLE
Problem about v-coco dataset

### ISSUE THREAD

**Issue by fangshuman** [MuchHair/HQM#1]
Thank you for your work.
How to set "dataset_file" when training on v-coco? 
And how to get "hoi.npy" and "bg.npy" for v-coco dataset? (line 37,38 in "datasets/vcoco_gt.py")

Thank you very much~

**Comment by MuchHair** [comment]
Thanks. You could follow our previous work https://github.com/SherlockHolmes221/DOQ for V-COCO dataset first. They are the same. We will update  the code as soon as possible.
