### ISSUE TITLE
detr-r50-pre.pth ( download problems) 

### ISSUE THREAD

**Issue by MArbane** [MuchHair/HQM#2]
Hello, 
I have faced a problem regarding  the "detr-r50-pre.pth", i can't download it from Baidu because I live overseas of china 

 How can I download this file any solution ?  

Thanks, 

Waiting for your reply

**Comment by MuchHair** [comment]
Thanks for your attention. The file is also available in Google Drive. https://drive.google.com/drive/folders/1ROqO99hQWl4eh4vhn6OopTxoHCvfNRUf
